"""empty message

Revision ID: cefb652a4efb
Revises: 22d5a1cab69f
Create Date: 2019-05-17 21:49:12.097263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cefb652a4efb'
down_revision = '22d5a1cab69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='roles')
    op.drop_column('roles', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('name', 'roles', ['name'], unique=True)
    # ### end Alembic commands ###
